// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleInfo: typeof import('./../views/ArticleInfo.vue')['default']
    ArticleList: typeof import('./../views/ArticleList.vue')['default']
    BlockAccount: typeof import('./../views/block/block-account.vue')['default']
    BlockFooter: typeof import('./../views/block/block-footer.vue')['default']
    BlockHeader: typeof import('./../views/block/block-header.vue')['default']
    BlockSideMenu: typeof import('./../views/block/block-sideMenu.vue')['default']
    DashboardPage: typeof import('./../views/DashboardPage.vue')['default']
    ElBtn: typeof import('./../components/input/el-btn.vue')['default']
    ElCanvasBg: typeof import('./../components/el-canvasBg.vue')['default']
    ElCheck: typeof import('./../components/input/el-check.vue')['default']
    ElCheckBox: typeof import('./../components/el-checkBox.vue')['default']
    ElDetail: typeof import('./../components/el-detail.vue')['default']
    ElFormGroup: typeof import('./../components/el-formGroup.vue')['default']
    ElGridTable: typeof import('./../components/el-gridTable.vue')['default']
    ElInput: typeof import('./../components/input/el-input.vue')['default']
    ElSectionBar: typeof import('./../components/el-sectionBar.vue')['default']
    ElSvgIcon: typeof import('./../components/el-svgIcon.vue')['default']
    ElTr: typeof import('./../components/el-tr.vue')['default']
    ElTreeItem: typeof import('./../components/el-treeItem.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HomePage: typeof import('./../views/HomePage.vue')['default']
    IconList: typeof import('./../views/IconList.vue')['default']
    LoginPage: typeof import('./../views/LoginPage.vue')['default']
    PageNotFound: typeof import('./../views/PageNotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionInfo: typeof import('./../views/SectionInfo.vue')['default']
    SectionList: typeof import('./../views/SectionList.vue')['default']
    UIUXSet: typeof import('./../views/UIUXSet.vue')['default']
  }
}
