// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    _footer: typeof import('./../views/block/_footer.vue')['default']
    _header: typeof import('./../views/block/_header.vue')['default']
    _sideMenu: typeof import('./../views/block/_sideMenu.vue')['default']
    Account: typeof import('./../views/Account.vue')['default']
    ElBtn: typeof import('./../components/el-btn.vue')['default']
    ElDetail: typeof import('./../components/el-detail.vue')['default']
    ElFormGroup: typeof import('./../components/el-formGroup.vue')['default']
    ElGridTable: typeof import('./../components/el-gridTable.vue')['default']
    ElImg: typeof import('./../components/el-img.vue')['default']
    ElInput: typeof import('./../components/el-input.vue')['default']
    ElSectionBar: typeof import('./../components/el-sectionBar.vue')['default']
    ElSvgIcon: typeof import('./../components/el-svgIcon.vue')['default']
    ElTreeItem: typeof import('./../components/el-treeItem.vue')['default']
    Footer: typeof import('./../views/block/footer.vue')['default']
    Header: typeof import('./../views/block/header.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Home: typeof import('./../views/Home.vue')['default']
    IconList: typeof import('./../views/IconList.vue')['default']
    IconList_back: typeof import('./../views/IconList_back.vue')['default']
    Login: typeof import('./../views/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./../views/block/sideMenu.vue')['default']
  }
}
